name: CI Build with Docker

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -f Dockerfile -t promptboard-ci .

      - name: Run CI Build
        run: docker run --rm promptboard-ci
