name: CI Build with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -f promptboard/Dockerfile -t promptboard-ci promptboard

      - name: Verify Build
        run: docker run --rm promptboard-ci npm run build
